# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(430, 650))
        MainWindow.setMaximumSize(QtCore.QSize(430, 650))
        font = QtGui.QFont()
        font.setFamily("Modern")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    background-color: rgb(48, 48, 48);\n"
"    color: rgb(48, 48, 48);\n"
"}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.page_1)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(34, 1, 0, 255), stop:1 rgba(182, 16, 53, 255));")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 15)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(26, 27, 34, 255), stop:1 rgba(86, 52, 62, 255));\n"
"border: none;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    font: 63 14pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.CurrentTrack = QtWidgets.QPushButton(self.widget_2)
        self.CurrentTrack.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.CurrentTrack.setFont(font)
        self.CurrentTrack.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"}\n"
"QPushButton::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"}\n"
"")
        self.CurrentTrack.setObjectName("CurrentTrack")
        self.horizontalLayout_18.addWidget(self.CurrentTrack)
        self.PlayCurrentTrack = QtWidgets.QPushButton(self.widget_2)
        self.PlayCurrentTrack.setMaximumSize(QtCore.QSize(70, 70))
        self.PlayCurrentTrack.setBaseSize(QtCore.QSize(0, 0))
        self.PlayCurrentTrack.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font: 63 22pt \"Segoe UI Semibold\";\n"
"}\n"
"QPushButton::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font: 63 22pt \"Segoe UI Semibold\";\n"
"}\n"
"")
        self.PlayCurrentTrack.setObjectName("PlayCurrentTrack")
        self.horizontalLayout_18.addWidget(self.PlayCurrentTrack)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TracksButton = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TracksButton.sizePolicy().hasHeightForWidth())
        self.TracksButton.setSizePolicy(sizePolicy)
        self.TracksButton.setMinimumSize(QtCore.QSize(0, 50))
        self.TracksButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 59, 63);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font: 63 22pt \"Segoe UI Semibold\";\n"
"}\n"
"QPushButton::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 59, 63);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font: 63 22pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"")
        self.TracksButton.setObjectName("TracksButton")
        self.horizontalLayout_2.addWidget(self.TracksButton)
        self.PlaylistsButton = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlaylistsButton.sizePolicy().hasHeightForWidth())
        self.PlaylistsButton.setSizePolicy(sizePolicy)
        self.PlaylistsButton.setMinimumSize(QtCore.QSize(0, 50))
        self.PlaylistsButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font: 63 22pt \"Segoe UI Semibold\";\n"
"}\n"
"QPushButton::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font: 63 22pt \"Segoe UI Semibold\";\n"
"}\n"
"")
        self.PlaylistsButton.setObjectName("PlaylistsButton")
        self.horizontalLayout_2.addWidget(self.PlaylistsButton)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(2, 2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.Tracks = QtWidgets.QListWidget(self.widget)
        self.Tracks.setStyleSheet("QListWidget {\n"
"    show-decoration-selected: 1;\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgba(255, 255, 255, 40);\n"
"    color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: rgba(255, 255, 255, 20);\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(148, 13, 41);\n"
"    width: 7px;\n"
"    margin: 0px 0 0 0;\n"
"    data:10\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(173, 68, 74);\n"
"    min-height: 5px;\n"
"    max-height: 6px;\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    color: rgba(255, 255, 255, 0);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    width: 0px;\n"
"    data:0\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"    border: none;\n"
"}")
        self.Tracks.setObjectName("Tracks")
        self.verticalLayout_4.addWidget(self.Tracks)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.AddTrackToPlayer = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddTrackToPlayer.sizePolicy().hasHeightForWidth())
        self.AddTrackToPlayer.setSizePolicy(sizePolicy)
        self.AddTrackToPlayer.setMinimumSize(QtCore.QSize(70, 70))
        self.AddTrackToPlayer.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(202, 79, 87);\n"
"border-radius: 35px;\n"
"font: 30pt \"MS Gothic\";\n"
"")
        self.AddTrackToPlayer.setObjectName("AddTrackToPlayer")
        self.horizontalLayout_17.addWidget(self.AddTrackToPlayer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 8)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_3 = QtWidgets.QWidget(self.page_2)
        self.widget_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(34, 1, 0, 255), stop:1 rgba(182, 16, 53, 255));")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 15)
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(26, 27, 34, 255), stop:1 rgba(86, 52, 62, 255));\n"
"border: none;")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.widget_7)
        self.label_2.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    font: 63 14pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.CurrentTrack_2 = QtWidgets.QPushButton(self.widget_7)
        self.CurrentTrack_2.setMinimumSize(QtCore.QSize(0, 70))
        self.CurrentTrack_2.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"}\n"
"QPushButton::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"}\n"
"")
        self.CurrentTrack_2.setObjectName("CurrentTrack_2")
        self.horizontalLayout_19.addWidget(self.CurrentTrack_2)
        self.PlayCurrentTrack_2 = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlayCurrentTrack_2.sizePolicy().hasHeightForWidth())
        self.PlayCurrentTrack_2.setSizePolicy(sizePolicy)
        self.PlayCurrentTrack_2.setMinimumSize(QtCore.QSize(70, 70))
        self.PlayCurrentTrack_2.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font: 63 22pt \"Segoe UI Semibold\";\n"
"}\n"
"QPushButton::pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font: 63 22pt \"Seg\n"
"}")
        self.PlayCurrentTrack_2.setObjectName("PlayCurrentTrack_2")
        self.horizontalLayout_19.addWidget(self.PlayCurrentTrack_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(5, 0, 5, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.TracksButton_2 = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TracksButton_2.sizePolicy().hasHeightForWidth())
        self.TracksButton_2.setSizePolicy(sizePolicy)
        self.TracksButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.TracksButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius: 25px;\n"
"font: 63 22pt \"Segoe UI Semibold\";\n"
"")
        self.TracksButton_2.setObjectName("TracksButton_2")
        self.horizontalLayout_6.addWidget(self.TracksButton_2)
        self.PlaylistsButton_2 = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlaylistsButton_2.sizePolicy().hasHeightForWidth())
        self.PlaylistsButton_2.setSizePolicy(sizePolicy)
        self.PlaylistsButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.PlaylistsButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 59, 63);\n"
"border: none;\n"
"border-radius: 25px;\n"
"font: 63 22pt \"Segoe UI Semibold\";\n"
"")
        self.PlaylistsButton_2.setObjectName("PlaylistsButton_2")
        self.horizontalLayout_6.addWidget(self.PlaylistsButton_2)
        self.verticalLayout_9.addWidget(self.widget_8)
        self.verticalLayout_9.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.Playlists = QtWidgets.QListWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Playlists.sizePolicy().hasHeightForWidth())
        self.Playlists.setSizePolicy(sizePolicy)
        self.Playlists.setMinimumSize(QtCore.QSize(0, 0))
        self.Playlists.setStyleSheet("QListWidget {\n"
"    show-decoration-selected: 1;\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgba(255, 255, 255, 40);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: rgba(255, 255, 255, 20);\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(148, 13, 41);\n"
"    width: 7px;\n"
"    margin: 0px 0 0 0;\n"
"    data:10\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(173, 68, 74);\n"
"    min-height: 5px;\n"
"    max-height: 6px;\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    color: rgba(255, 255, 255, 0);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    width: 0px;\n"
"    data:0\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"    border: none;\n"
"}")
        self.Playlists.setObjectName("Playlists")
        self.verticalLayout_8.addWidget(self.Playlists)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.AddPlaylist = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddPlaylist.sizePolicy().hasHeightForWidth())
        self.AddPlaylist.setSizePolicy(sizePolicy)
        self.AddPlaylist.setMinimumSize(QtCore.QSize(70, 70))
        self.AddPlaylist.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AddPlaylist.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(202, 79, 87);\n"
"border-radius: 35px;\n"
"font: 45pt \"MS Gothic\";\n"
"")
        self.AddPlaylist.setObjectName("AddPlaylist")
        self.horizontalLayout_3.addWidget(self.AddPlaylist)
        self.DeletePlaylists = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeletePlaylists.sizePolicy().hasHeightForWidth())
        self.DeletePlaylists.setSizePolicy(sizePolicy)
        self.DeletePlaylists.setMinimumSize(QtCore.QSize(70, 70))
        self.DeletePlaylists.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(202, 79, 87);\n"
"border-radius: 35px;\n"
"font: 25pt \"MS Gothic\";\n"
"")
        self.DeletePlaylists.setObjectName("DeletePlaylists")
        self.horizontalLayout_3.addWidget(self.DeletePlaylists)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 8)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addWidget(self.widget_3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_11)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.widget_9 = QtWidgets.QWidget(self.page_11)
        self.widget_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(34, 1, 0, 255), stop:1 rgba(182, 16, 53, 255));")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(3)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_10.setStyleSheet("background-color: rgb(58, 68, 76);\n"
"border: none;")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.PlaylistDeleteBack = QtWidgets.QPushButton(self.widget_10)
        self.PlaylistDeleteBack.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.PlaylistDeleteBack.setObjectName("PlaylistDeleteBack")
        self.horizontalLayout_15.addWidget(self.PlaylistDeleteBack)
        self.label_4 = QtWidgets.QLabel(self.widget_10)
        self.label_4.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    font: 63 16pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_15.addWidget(self.label_4)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 7)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.verticalLayout_24.addWidget(self.widget_10)
        self.PlaylistToDelete = QtWidgets.QListWidget(self.widget_9)
        self.PlaylistToDelete.setStyleSheet("QListWidget {\n"
"    show-decoration-selected: 1;\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgba(255, 255, 255, 40);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: rgba(255, 255, 255, 20);\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(148, 13, 41);\n"
"    width: 7px;\n"
"    margin: 0px 0 0 0;\n"
"    data:10\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(173, 68, 74);\n"
"    min-height: 5px;\n"
"    max-height: 6px;\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    color: rgba(255, 255, 255, 0);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    width: 0px;\n"
"    data:0\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"    border: none;\n"
"}")
        self.PlaylistToDelete.setObjectName("PlaylistToDelete")
        self.verticalLayout_24.addWidget(self.PlaylistToDelete)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.DeleteSelectedPlaylistButton = QtWidgets.QPushButton(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteSelectedPlaylistButton.sizePolicy().hasHeightForWidth())
        self.DeleteSelectedPlaylistButton.setSizePolicy(sizePolicy)
        self.DeleteSelectedPlaylistButton.setMinimumSize(QtCore.QSize(70, 70))
        self.DeleteSelectedPlaylistButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(202, 79, 87);\n"
"border-radius: 35px;\n"
"font: 25pt \"MS Gothic\";\n"
"")
        self.DeleteSelectedPlaylistButton.setObjectName("DeleteSelectedPlaylistButton")
        self.horizontalLayout_16.addWidget(self.DeleteSelectedPlaylistButton)
        self.verticalLayout_24.addLayout(self.horizontalLayout_16)
        self.verticalLayout_24.setStretch(0, 1)
        self.verticalLayout_23.addLayout(self.verticalLayout_24)
        self.verticalLayout_25.addWidget(self.widget_9)
        self.stackedWidget.addWidget(self.page_11)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_11 = QtWidgets.QWidget(self.page_9)
        self.widget_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(34, 1, 0, 255), stop:1 rgba(182, 16, 53, 255));")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_12 = QtWidgets.QWidget(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.21, y1:0.142273, x2:0.773, y2:1, stop:0 rgba(59, 0, 37, 255), stop:1 rgba(84, 7, 59, 255));\n"
"border: none;")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(10, 0, 3, 10)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.PlaylistBack = QtWidgets.QPushButton(self.widget_12)
        self.PlaylistBack.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.PlaylistBack.setObjectName("PlaylistBack")
        self.horizontalLayout_8.addWidget(self.PlaylistBack)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.PlayPlaylist = QtWidgets.QPushButton(self.widget_12)
        self.PlayPlaylist.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.PlayPlaylist.setObjectName("PlayPlaylist")
        self.horizontalLayout_8.addWidget(self.PlayPlaylist)
        self.AddTrackToPlaylist = QtWidgets.QPushButton(self.widget_12)
        self.AddTrackToPlaylist.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.AddTrackToPlaylist.setObjectName("AddTrackToPlaylist")
        self.horizontalLayout_8.addWidget(self.AddTrackToPlaylist)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setContentsMargins(30, -1, -1, -1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.PlaylistName = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlaylistName.sizePolicy().hasHeightForWidth())
        self.PlaylistName.setSizePolicy(sizePolicy)
        self.PlaylistName.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.PlaylistName.setFont(font)
        self.PlaylistName.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    font: 63 18pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.PlaylistName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PlaylistName.setObjectName("PlaylistName")
        self.verticalLayout_21.addWidget(self.PlaylistName)
        self.PlaylistInfo = QtWidgets.QLabel(self.widget_12)
        self.PlaylistInfo.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    font: 63 12pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.PlaylistInfo.setObjectName("PlaylistInfo")
        self.verticalLayout_21.addWidget(self.PlaylistInfo)
        self.verticalLayout_13.addLayout(self.verticalLayout_21)
        self.horizontalLayout_9.addLayout(self.verticalLayout_13)
        self.verticalLayout_12.addWidget(self.widget_12)
        self.PlaylistTracks = QtWidgets.QListWidget(self.widget_11)
        self.PlaylistTracks.setStyleSheet("QListWidget {\n"
"    show-decoration-selected: 1;\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgba(255, 255, 255, 40);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: rgba(255, 255, 255, 20);\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(148, 13, 41);\n"
"    width: 7px;\n"
"    margin: 0px 0 0 0;\n"
"    data:10\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(173, 68, 74);\n"
"    min-height: 5px;\n"
"    max-height: 6px;\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    border: none;\n"
"}")
        self.PlaylistTracks.setObjectName("PlaylistTracks")
        self.verticalLayout_12.addWidget(self.PlaylistTracks)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 4)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addWidget(self.widget_11)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.widget_5 = QtWidgets.QWidget(self.page_10)
        self.widget_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(34, 1, 0, 255), stop:1 rgba(182, 16, 53, 255));")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_6.setStyleSheet("background-color: rgb(58, 68, 76);\n"
"border: none;")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, 0, 15, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.TrackToAddBack = QtWidgets.QPushButton(self.widget_6)
        self.TrackToAddBack.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.TrackToAddBack.setObjectName("TrackToAddBack")
        self.horizontalLayout_7.addWidget(self.TrackToAddBack)
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        self.label_3.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    font: 63 16pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.ClearTracksSelection = QtWidgets.QPushButton(self.widget_6)
        self.ClearTracksSelection.setStyleSheet("border: none;\n"
"font: 63 24pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ClearTracksSelection.setObjectName("ClearTracksSelection")
        self.horizontalLayout_7.addWidget(self.ClearTracksSelection)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 7)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_20.addWidget(self.widget_6)
        self.TracksToAdd = QtWidgets.QListWidget(self.widget_5)
        self.TracksToAdd.setStyleSheet("QListWidget {\n"
"    show-decoration-selected: 1;\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgba(255, 255, 255, 40);\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: rgba(255, 255, 255, 20);\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(148, 13, 41);\n"
"    width: 7px;\n"
"    margin: 0px 0 0 0;\n"
"    data:10\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(173, 68, 74);\n"
"    min-height: 5px;\n"
"    max-height: 6px;\n"
"    border-radius: 3px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    color: rgba(255, 255, 255, 0);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    width: 0px;\n"
"    data:0\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"    border: none;\n"
"}")
        self.TracksToAdd.setObjectName("TracksToAdd")
        self.verticalLayout_20.addWidget(self.TracksToAdd)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.AddSelectedTracksToPlaylistButton = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddSelectedTracksToPlaylistButton.sizePolicy().hasHeightForWidth())
        self.AddSelectedTracksToPlaylistButton.setSizePolicy(sizePolicy)
        self.AddSelectedTracksToPlaylistButton.setMinimumSize(QtCore.QSize(70, 70))
        self.AddSelectedTracksToPlaylistButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(202, 79, 87);\n"
"border-radius: 35px;\n"
"font: 25pt \"MS Gothic\";\n"
"")
        self.AddSelectedTracksToPlaylistButton.setObjectName("AddSelectedTracksToPlaylistButton")
        self.horizontalLayout_13.addWidget(self.AddSelectedTracksToPlaylistButton)
        self.verticalLayout_20.addLayout(self.horizontalLayout_13)
        self.verticalLayout_20.setStretch(0, 1)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.verticalLayout_22.addWidget(self.widget_5)
        self.stackedWidget.addWidget(self.page_10)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_13 = QtWidgets.QWidget(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.506, fy:0.681818, stop:0.00568182 rgba(37, 0, 22, 255), stop:1 rgba(55, 4, 37, 255));")
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_15.setContentsMargins(15, 10, 15, 20)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(15, 10, 15, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.TrackBack = QtWidgets.QPushButton(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TrackBack.sizePolicy().hasHeightForWidth())
        self.TrackBack.setSizePolicy(sizePolicy)
        self.TrackBack.setMinimumSize(QtCore.QSize(50, 50))
        self.TrackBack.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.TrackBack.setObjectName("TrackBack")
        self.horizontalLayout_10.addWidget(self.TrackBack)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.GetInfo = QtWidgets.QPushButton(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GetInfo.sizePolicy().hasHeightForWidth())
        self.GetInfo.setSizePolicy(sizePolicy)
        self.GetInfo.setMinimumSize(QtCore.QSize(50, 50))
        self.GetInfo.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.GetInfo.setObjectName("GetInfo")
        self.horizontalLayout_10.addWidget(self.GetInfo)
        self.horizontalLayout_10.setStretch(1, 5)
        self.verticalLayout_15.addLayout(self.horizontalLayout_10)
        self.widget_15 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setMinimumSize(QtCore.QSize(200, 200))
        self.widget_15.setAutoFillBackground(False)
        self.widget_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15.addWidget(self.widget_15)
        self.widget_14 = QtWidgets.QWidget(self.widget_13)
        self.widget_14.setStyleSheet("border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.PreviousTrackButton = QtWidgets.QPushButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreviousTrackButton.sizePolicy().hasHeightForWidth())
        self.PreviousTrackButton.setSizePolicy(sizePolicy)
        self.PreviousTrackButton.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.PreviousTrackButton.setObjectName("PreviousTrackButton")
        self.horizontalLayout_11.addWidget(self.PreviousTrackButton)
        self.PauseTrackButton = QtWidgets.QPushButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PauseTrackButton.sizePolicy().hasHeightForWidth())
        self.PauseTrackButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.PauseTrackButton.setFont(font)
        self.PauseTrackButton.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.PauseTrackButton.setObjectName("PauseTrackButton")
        self.horizontalLayout_11.addWidget(self.PauseTrackButton)
        self.NextTrackButton = QtWidgets.QPushButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextTrackButton.sizePolicy().hasHeightForWidth())
        self.NextTrackButton.setSizePolicy(sizePolicy)
        self.NextTrackButton.setStyleSheet("border: none;\n"
"font: 63 26pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.NextTrackButton.setObjectName("NextTrackButton")
        self.horizontalLayout_11.addWidget(self.NextTrackButton)
        self.verticalLayout_18.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.CurrentTrackTime = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentTrackTime.sizePolicy().hasHeightForWidth())
        self.CurrentTrackTime.setSizePolicy(sizePolicy)
        self.CurrentTrackTime.setMinimumSize(QtCore.QSize(50, 20))
        self.CurrentTrackTime.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    font: 63 12pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.CurrentTrackTime.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentTrackTime.setObjectName("CurrentTrackTime")
        self.horizontalLayout_12.addWidget(self.CurrentTrackTime)
        self.TrackProgressBar = QtWidgets.QSlider(self.widget_14)
        self.TrackProgressBar.setStyleSheet("QSlider::groove:horizontal { \n"
                                            "    background-color: rgb(115, 115, 115);\n"
                                            "    border: 0px solid #424242; \n"
                                            "    height: 2px; \n"
                                            "    border-radius: 4px;\n"
                                            "}\n"
                                            "\n"
                                            "QSlider::handle:horizontal { \n"
                                            "    background-color: rgb(197, 82, 94);\n"
                                            "    width: 10px; \n"
                                            "    height: 10px; \n"
                                            "    line-height: 20px; \n"
                                            "    margin-top: -5px; \n"
                                            "    margin-bottom: -5px; \n"
                                            "    border-radius: 5px; \n"
                                            "}\n"
                                            "")
        self.TrackProgressBar.setMaximum(1000)
        self.TrackProgressBar.setPageStep(1)
        self.TrackProgressBar.setProperty("data", 0)
        self.TrackProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.TrackProgressBar.setObjectName("TrackProgressBar")
        self.horizontalLayout_12.addWidget(self.TrackProgressBar)
        self.TrackTime = QtWidgets.QLabel(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TrackTime.sizePolicy().hasHeightForWidth())
        self.TrackTime.setSizePolicy(sizePolicy)
        self.TrackTime.setMinimumSize(QtCore.QSize(50, 20))
        self.TrackTime.setStyleSheet("QLabel{\n"
                                     "    border: none;\n"
                                     "    font: 63 12pt \"Segoe UI Semibold\";\n"
                                     "    color: rgb(255, 255, 255);\n"
                                     "    background-color: rgba(255, 255, 255, 0);\n"
                                     "}")
        self.TrackTime.setAlignment(QtCore.Qt.AlignCenter)
        self.TrackTime.setObjectName("TrackTime")
        self.horizontalLayout_12.addWidget(self.TrackTime)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 5)
        self.horizontalLayout_12.setStretch(2, 1)
        self.verticalLayout_18.addLayout(self.horizontalLayout_12)
        self.verticalLayout_15.addWidget(self.widget_14)
        self.TrackNameInTrackMenu = QtWidgets.QLabel(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TrackNameInTrackMenu.sizePolicy().hasHeightForWidth())
        self.TrackNameInTrackMenu.setSizePolicy(sizePolicy)
        self.TrackNameInTrackMenu.setMinimumSize(QtCore.QSize(0, 30))
        self.TrackNameInTrackMenu.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                "border: none;\n"
                                                "border-radius: 25px;\n"
                                                "font: 63 14pt \"Segoe UI Semibold\";\n"
                                                "background-color: rgba(255, 255, 255, 0);")
        self.TrackNameInTrackMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.TrackNameInTrackMenu.setObjectName("TrackNameInTrackMenu")
        self.verticalLayout_15.addWidget(self.TrackNameInTrackMenu)
        self.verticalLayout_15.setStretch(0, 2)
        self.verticalLayout_15.setStretch(1, 8)
        self.verticalLayout_15.setStretch(2, 3)
        self.verticalLayout_2.addWidget(self.widget_13)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "     Сейчас играет:"))
        self.CurrentTrack.setText(_translate("MainWindow", "PushButton"))
        self.PlayCurrentTrack.setText(_translate("MainWindow", "⯈"))
        self.TracksButton.setText(_translate("MainWindow", "ВСЕ ТРЕКИ"))
        self.PlaylistsButton.setText(_translate("MainWindow", "ПЛЕЙЛИСТЫ"))
        self.AddTrackToPlayer.setText(_translate("MainWindow", "𝅘𝅥𝅮+"))
        self.label_2.setText(_translate("MainWindow", "     Сейчас играет:"))
        self.CurrentTrack_2.setText(_translate("MainWindow", "PushButton"))
        self.PlayCurrentTrack_2.setText(_translate("MainWindow", "⯈"))
        self.TracksButton_2.setText(_translate("MainWindow", "ВСЕ ТРЕКИ"))
        self.PlaylistsButton_2.setText(_translate("MainWindow", "ПЛЕЙЛИСТЫ"))
        self.AddPlaylist.setText(_translate("MainWindow", "+"))
        self.DeletePlaylists.setText(_translate("MainWindow", "🗑️"))
        self.PlaylistDeleteBack.setText(_translate("MainWindow", "🡠"))
        self.label_4.setText(_translate("MainWindow", "Выберите плейлисты"))
        self.DeleteSelectedPlaylistButton.setText(_translate("MainWindow", "🗑️"))
        self.PlaylistBack.setText(_translate("MainWindow", " 🡠 "))
        self.PlayPlaylist.setText(_translate("MainWindow", "⯈"))
        self.AddTrackToPlaylist.setText(_translate("MainWindow", "𝅘𝅥𝅮+"))
        self.PlaylistName.setText(_translate("MainWindow", "Название плейлиста"))
        self.PlaylistInfo.setText(_translate("MainWindow", ""))
        self.TrackToAddBack.setText(_translate("MainWindow", "🡠"))
        self.label_3.setText(_translate("MainWindow", "Выберите треки"))
        self.ClearTracksSelection.setText(_translate("MainWindow", "🗑️"))
        self.AddSelectedTracksToPlaylistButton.setText(_translate("MainWindow", "✔"))
        self.TrackBack.setText(_translate("MainWindow", "🡠"))
        self.GetInfo.setText(_translate("MainWindow", "?"))
        self.PreviousTrackButton.setText(_translate("MainWindow", "⯇⯇"))
        self.PauseTrackButton.setText(_translate("MainWindow", "⯈"))
        self.NextTrackButton.setText(_translate("MainWindow", "⯈⯈"))
        self.CurrentTrackTime.setText(_translate("MainWindow", "0:00"))
        self.TrackTime.setText(_translate("MainWindow", ""))
        self.TrackNameInTrackMenu.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
